spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lab1_fsbs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none